Object subclass: Item [

    Item class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]

]

Item subclass: Ladle [

    Ladle class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: FeatherDuster [

    FeatherDuster class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]
]

Item subclass: Rake [

    Rake class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: ToolHandle [

    ToolHandle class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: ToolPart [

    ToolPart class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: VaultKey [

    VaultKey class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: ButlersKeys [

    ButlersKeys class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: Diamond [

    Diamond class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: CoinPouch [

    CoinPouch class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: Mushroom [

    Mushroom class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]    
]

Item subclass: Dirt [

    Dirt class >> new [
        | i |
        i := super new.
        i init.
        ^i
    ]
]